### ISSUE TITLE
Collaborators tweaks after review

### ISSUE THREAD

**Issue by pmaier1** [owncloud/phoenix#1186]
Moved to https://github.com/owncloud/enterprise/blob/master/product/oc10/index.md#collaborators

# Tasks

**Comment by butonic** [comment]
Linking [this](https://www.roth-digital.de/wp-content/uploads/2018/08/FileServiceNCloud_Slides_19_post.pdf) here because the university of augsburg implmentet sharing on top of NFSv4 ACLs back in 2016. On slide 33 they present their mapping of oc CRUDS permissions to ACLs.

**Comment by pmaier1** [comment]
**Feedback from first testing**

- Opening left sidebar moves the whole screen (including e.g., the account indicator on the top right) => feels strange => intended?
- Logout/Exit does not log out

- The currently logged in user's name should be shown as "You" (e.g. as Owner)
- File list
  - Clicking on a file does not select it but highlight => intended?
  - Views are missing
    - Shared with you
    - Shared with others
    - Shared by link

- Considerations UX fheidecke https://github.com/owncloud/phoenix/issues/1640 => very valid, IMO

- Adding/modifying collaborators
  - Too less visible separation and guidance between the elements
  - Roles: Need better explanation text
  - Roles: Explanation text only needs to be shown in the picker, not again below
  - No way to undo changes instead of saving them
  - Bug: Switching from "custom role" to another role does only reload the permission checkboxes if you save
  - Custom role: Making changes after saving does not enable the save button again; can also happen when changing from "custom role" to another role
  - Single file: "Custom role" shows "can change" instead of "Edit"
  - You can't find users by their user name if a display name is set
  - You can't find users by their mail address
  - "Extra field to display in autocomplete results" is not respected
  - Selected collaborators could be fixed within the autocomplete input field, not below
  - Federated sharing does not work
  - Guest sharing does not work

- Autocomplete
  - Existing collaborators are still shown => can even (try to) add existing collaborators
  - Avatars are not shown
  - Additional information (e.g. "Extra field to display in autocomplete results") is not shown

- Collaborator list
  - Reshare indicator appears even if it's not a reshare
  - "Custom role" is shown for "Editor/Viewer + can share"
  - Do we need a count for Collaborators AND users AND groups??
  - Trash bin icon to remove a collaborator maybe not appropriate?
  - Closing an "edit" dialog without saving may cause human mistakes
  - (+) symbol to expand collaborators is not intuitive
  - If reshare is not possible (e.g., disabled or no permission) users can still add collaborators but it fails
  - When the list takes some time to load, there's no spinner/indicator
  - Avatars are dummies
  - A reshare recipient can't recognize the resharer

- File list
  - No indication that a resource is shared
    - Requirements: Should also be possible for subitems of a shared folder
  - No indication that a resource has been received from another user
    - Requirements: Should also be possible for subitems of a shared folder
  - The user can't conduct any actions in the current folder (e.g. add collaborators)

- Collaborators can't recognize their role/permissions => Show role + explanation text somewhere
  - Requirements: Should also be possible for subitems of a shared folder

**Comment by PVince81** [comment]
Found in ee3b72eb083085296d0bde9da2f40a049d585d63 today:

- [ ] in "Shared with me" and "Shared with others", assuming we want the same design like in OC 10:
    - [ ] clicking on a folder must redirect to the actual folder in the "All files" view
    - [ ] a trash icon must be available to "unshare from self"
    - [ ] actions for accept/deny for pending shares (to verify)

**Comment by LukasHirt** [comment]
> actions for accept/deny for pending shares (to verify)

Should be implemented.

**Comment by PVince81** [comment]
I've raised tickets for all the items. @pmaier1 you might want to review them and provide more information there in case it's not clear enough.

**Comment by PVince81** [comment]
One more to add:

- [ ] "Add Collaborators" panel is missing avatars after selecting a few users or groups to share to

**Comment by PVince81** [comment]
- [ ] Add a margin bottom to "You don't have permission..." 

![image](https://user-images.githubusercontent.com/277525/73547772-e8f1a380-443f-11ea-8906-faf4215549da.png)

**Comment by PVince81** [comment]
- [ ] Collaborator autocomplete must clear text field after selecting

**Comment by kulmann** [comment]
- [ ] In the new share panel, selecting a user share excludes a group share with the same name from the list of candidates. Need to check for `shareWith` AND `shareType`, not only `shareWith`
