### ISSUE TITLE
File List feature

### ISSUE THREAD

**Issue by PVince81** [owncloud/phoenix#150]
Ticket to track requirements and progress on the file list feature.
A task is done when the file list was wired up already to the APIs (no dummy)

- [x] list files
- [ ] file actions: see https://github.com/owncloud/phoenix/issues/149
- [x] delete single file
- [x] delete multiple files
- [x] select/deselct multiple files for bulk actions
- [x] select/deselct all files for bulk actions
- [x] rename single file
- [x] create new folder
- [ ] create new file (TODO: ticket for extensibility of file formats like text editor, etc, like NewFileMenu in core) https://github.com/owncloud/phoenix/issues/274
- [x] move selected entries to subfolder with drag and drop
- [x] drag to breadcrumb to move to parent folder
- [x] breadcrumbs
- [x] file download
- [ ] file upload (with and without chunking) https://github.com/owncloud/phoenix/issues/67
- [ ] progress bar for operations
- [ ] spinners / state for all operations
- [x] sidebar (to be tracked in detail in a separate ticket)

@OshanIvantha @felixheidecke please update accordingly and link to tickets and PRs

**Comment by PVince81** [comment]
https://github.com/owncloud/phoenix/issues/275
