### ISSUE TITLE
GSOC Milestone Tracking

### ISSUE THREAD

**Issue by labkode** [owncloud/phoenix#155]
# Milestones for the Petabyte-Scale Cloud Storage File Manager  GSOC project

## M1. Community Bonding
- [x] M1.1 Get to know the community better
- [x] M1.2 Learn about the CERN, ownCloud and AARNet organizations
- [x] M1.3 Learn about the tools that will be used
- [x] M1.4 Get familiar with Phoenix

## M2. Implement the Files and Sharing functionalities
**Evaluation: 11th June**
- [x] M2.1 Implement file browsing
- [ ] M2.2 Implement data upload and data download
- [ ] M2.3 Implement the public link functionality
- [ ] M2.4 Implement the sharing functionality
- [x] M2.5 Perform test of various corner cases than can arise
- [x] M2.6 Ensure proper documentation of the written code

**Comment by labkode** [comment]
@DeepDiver1975 @OshanIvantha @felixheidecke @PVince81 
We can track here Ivantha's progress for the GSOC project

**Comment by DeepDiver1975** [comment]
GSoC is over. Thanks a lot @OshanIvantha
