### ISSUE TITLE
Project Overview first app release

### ISSUE THREAD

**Issue by felixheidecke** [owncloud/phoenix#168]
Tasks that need to be taken care of:

- [ ] [Single Vue Instance](https://github.com/owncloud/phoenix/pull/163) est. 1d
- [ ] [Sharing sidebar app](https://github.com/owncloud/phoenix/issues/37) est. 3d
- [x] ~~[Authentication layer](https://github.com/owncloud/phoenix/issues/42) est. TBD~~ => likely too much, let's focus on basic auth for the first version
- [ ] [Allow apps to register to a connected event](https://github.com/owncloud/phoenix/issues/80) est. 2h
- [ ] [elements need unique identifier](https://github.com/owncloud/phoenix/issues/153) est. 1/2 day
- [ ] [js-owncloud-client packaging](https://github.com/owncloud/js-owncloud-client/issues/79)

**Comment by PVince81** [comment]
- [ ] make it clear that demos are demos (label "Demo", etc)

Goal is to have Phoenix installable as app and usable:

- [ ] ability to switch between Phoenix and old UI
    - add link to Phoenix in login page: in Phoenix use basic auth
    - should login popup of Phoenix appear right away ?

- [ ] authentication of old UI must also work in Phoenix through cookie / magic (if applicable)

**Comment by PVince81** [comment]
- [ ] basic automated tests ready (login works, file list can be displayed)

once we have all these we could release the first Phoenix version as marketplace app and get more people to try it out.

Then figure out the next steps.

**Comment by PVince81** [comment]
- [ ] raise release ticket for release planning

**Comment by PVince81** [comment]
can we close this ?

@DeepDiver1975
