### ISSUE TITLE
Orga / tickets for milestone 1

### ISSUE THREAD

**Issue by PVince81** [owncloud/phoenix#2024]
We have many checkboxes in many places for milestone 1.

I'd like to gather those and raise tickets so that milestone 1 will represent our backlog for that milestone.

**Comment by PVince81** [comment]
Goal is to have one ticket per task and have the ticket list in milestone 1 be exhaustive.

**Comment by PVince81** [comment]
- [ ] sort milestone according to priorities (must have vs nice to have)

**Comment by PVince81** [comment]
- [ ] split tasks into smaller milestones for easier delivery

**Comment by PVince81** [comment]
- [ ] raise tickets for "links" feedback ticket https://github.com/owncloud/phoenix/issues/1307

**Comment by PVince81** [comment]
I'll need some time to think about a way to split into smaller milestones.

For now we'll simply schedule sprint items by looking at the Github milestone order. So grouping of tasks could be done by putting them closer in the Github milestone.
