### ISSUE TITLE
Collaborators panel UX fixes

### ISSUE THREAD

**Issue by PVince81** [owncloud/phoenix#2059]
- [x] Accordion / layout confusion: https://github.com/owncloud/phoenix/issues/1908 => accordion is gone
- [x] Inconsistent role interaction: https://github.com/owncloud/phoenix/issues/1907 => roles selection has been improved

From https://github.com/owncloud/phoenix/issues/1186:
- [ ] Roles: Need better explanation text
- [ ] Roles: Explanation text only needs to be shown in the picker, not again below
- [ ] Selected collaborators could be fixed within the autocomplete input field, not below
- [x] Trash bin icon to remove a collaborator maybe not appropriate? => adjusted
- [ ] Closing an "edit" dialog without saving may cause human mistakes
- [x] (+) symbol to expand collaborators is not intuitive => removed
- [ ] Collaborators can't recognize their role/permissions => Show role + explanation text somewhere

**Comment by PVince81** [comment]
<img width="574" alt="image" src="https://user-images.githubusercontent.com/277525/66812454-339fec00-ef33-11e9-96ff-39feb80fee40.png">

@wuenschedesign

**Comment by PVince81** [comment]
<img width="568" alt="image" src="https://user-images.githubusercontent.com/277525/66812491-45818f00-ef33-11e9-8204-a34fe26f097f.png">

**Comment by PVince81** [comment]
- [ ] include private link: https://github.com/owncloud/phoenix/issues/2218

**Comment by PVince81** [comment]
closing in favor of https://github.com/owncloud/phoenix/issues/1186
