### ISSUE TITLE
Remove filter button

### ISSUE THREAD

**Issue by PVince81** [owncloud/phoenix#2971]
The filter button on the top right is confusing and needs to be reworked.

In the meantime we (with @pmaier1) decided to remove it altogether for the Phoenix MVP milestone.

The filter button contains the following pieces:
- only show files or folders: there was never a requirement for this, we should remove this completely
- checkbox for showing hidden files: for now we make it default to true
- search box for the local folder: users should use the search in the top bar. In general we'll likely want to have only a single search box and have the search results split between "locally visible entries" and "resources in other folders" like we had in OC 10.

### Tasks

- [ ] Remove filter button on the top right
- [ ] Make hidden files visible by default
- [ ] Raise tickets for the proper design + implementation
    - [ ] search box results for local folder
    - [ ] checkbox for hidden files

**Comment by PVince81** [comment]
PR here https://github.com/owncloud/phoenix/pull/2972
