### ISSUE TITLE
[Tests-only] Improve ocis test using phoenix

### ISSUE THREAD

**Issue by dpakach** [owncloud/phoenix#3129]
### Improve test cases to support running using the OCIS backend
- [x]  Handle clearing versions in tests using redis server. (https://github.com/owncloud/ocis-reva/issues/110)
- [x]  Handle tests to use proper file path in trashbin while running using OCIS (https://github.com/owncloud/ocis-reva/issues/112)
- [x]  Response from the trashbin API is not parsable and throws error (need to investigate and open issue in the reva repo) (https://github.com/owncloud/ocis-reva/issues/111)

**This issue will only be applicable after  #2914 is merged**

**Comment by dpakach** [comment]
All tasks done or moved to new issue
