### ISSUE TITLE
Phoenix 0.1.0 Release

### ISSUE THREAD

**Issue by PVince81** [owncloud/phoenix#41]
I suggest to aim for the following goals to be able to have a first beta release of the Phoenix project:

- [x] organize the code in a way that makes it packagable as a marketplace app: https://github.com/owncloud/phoenix/issues/40
- [x] one vue to rule them all https://github.com/owncloud/phoenix/issues/146
- [ ] Separate phoenix scaffold from files_app https://github.com/owncloud/phoenix/issues/55
- [ ] individual components/apps must be packageable as well, for example:
   - [ ] files app ?
   - [ ] file list: https://github.com/owncloud/phoenix/issues/150
   - [ ] sharing frontend (sidebar): https://github.com/owncloud/phoenix/issues/37
- [ ] build scripts for release
- [x] baseline for JS unit test / acceptance tests

@DeepDiver1975 @felixheidecke @pmaier1 @patrickjahns

**Comment by PVince81** [comment]
note: it is likely possible to do an alpha release with even less than that

**Comment by PVince81** [comment]
@felixheidecke let's use this ticket as the highest level ticket for the first Phoenix release.

Please check the above list and add things you think are missing.

**Comment by PVince81** [comment]
I've ticked "one vue to rule them all"

**Comment by PVince81** [comment]
@felixheidecke please adjust the checkbox list.

I think we need to check that Phoenix is able to use the current auth when running as app inside of OC

**Comment by felixheidecke** [comment]
The [File upload feature](https://github.com/owncloud/phoenix/pull/166) had to be closed due to problems with uploads in js-owncloud-client.

**Comment by PVince81** [comment]
@felixheidecke we still need a ticket to track it as I think we should have at least basic upload (non chunking) for the first version

**Comment by PVince81** [comment]
@DeepDiver1975 reuse this or make a new release ticket ?

**Comment by DeepDiver1975** [comment]
scope of 0.1.0 changed a bit - please have a look at https://github.com/owncloud/phoenix/projects/1#card-13283788

**Comment by DeepDiver1975** [comment]
we are basically done

**Comment by PVince81** [comment]
@DeepDiver1975 then I suggest closing this and doing another release ticket for the next iteration maybe
