### ISSUE TITLE
Bootstrap owncloud-design-system

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/phoenix#730]
# Background
- vuetify did not bring us that far then originally expected
- a pattern library is what we need
- we did choose vueds

# ToDos
- [x] create new repo https://github.com/owncloud/owncloud-design-system
- [x] get vueds bootstrapped inside
- [x] deploy docs to github pages
- [x] incorporate UiKit
- [ ] build initial components based currently used vuetify components
- [x] incorporate phoenix theme - https://github.com/owncloud/phoenix/tree/master/src/themes/owncloud
- [ ] publish npm package to npmjs.com
- [ ] integrate design-system in phoenix
- [ ] research into theming capabilities (fork, adjust and rebuild css?)

**Comment by butonic** [comment]
what did not work out in vuetify?
just stumbled over https://github.com/creativetimofficial/material-kit ?

**Comment by scramb** [comment]
vuetify is really bound to material-design, which is not bad; But does limit us aswell to material-design guidelines. This does not always fit our needs and is more code to write to make it work as desired/needed. 
On the long run i believe we can get closer to the requirements as ever before if we put in the right motivation to build up a good pattern library .

**Comment by DeepDiver1975** [comment]
its alive ->close
